### ISSUE TITLE
Feature request: Controlling Dryer

### ISSUE THREAD

**Issue by TomHom91** [pySmartThings/pysmartthings#202]
Hi there,

With the old PAT I was able to controle my dryer with the following Shell command:
```
shell_command:
  droger_start: 'curl --location --request POST ''https://api.smartthings.com/v1/devices/8cddb6a7-6722-5169-bd09-************/commands'' --header ''Authorization: Bearer 42658c1c-fc08-4a8a-9633-************'' --header ''Content-Type: text/plain'' --data-raw ''[    {   "capability":"dryerOperatingState",        "command":"setMachineState",        "arguments":["run"]    }]'''
  droger_pause: 'curl --location --request POST ''https://api.smartthings.com/v1/devices/8cddb6a7-6722-5169-bd09-************/commands'' --header ''Authorization: Bearer 42658c1c-fc08-4a8a-9633-************'' --header ''Content-Type: text/plain'' --data-raw ''[    {   "capability":"dryerOperatingState",        "command":"setMachineState",        "arguments":["pause"]    }]'''
  droger_stop: 'curl --location --request POST ''https://api.smartthings.com/v1/devices/8cddb6a7-6722-5169-bd09-************/commands'' --header ''Authorization: Bearer 42658c1c-fc08-4a8a-9633-************'' --header ''Content-Type: text/plain'' --data-raw ''[    {   "capability":"dryerOperatingState",        "command":"setMachineState",        "arguments":["stop"]    }]'''

```

As the PAT don't work anymore, is there a possibility to add this to the integration?

Thanks and keep up the good work! 🥇
